import type { Models } from 'node-appwrite'

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types src/types`.

export enum GoalType {
  IN_GAME = 'InGame',
  FREE_KICK = 'FreeKick',
  PENALTY = 'Penalty',
}

export type Assists = Models.Row & {
  round: number
  player: number
  amount: number
  season: string
}

export type Goals = Models.Row & {
  round: number
  player: number
  amount: number
  season: string
  goal_type: GoalType
}

export type Lineups = Models.Row & {
  round: number
  player: number
  position: number
  season: string
}

export type Matches = Models.Row & {
  round: number
  goals_scored: number | null
  goals_conceded: number | null
  datetime: string | null
  season: string
  played: boolean
  opponent: Teams
}

export type PenaltiesAgainst = Models.Row & {
  round: number
  player: number
  amount: number
  saved: number
  season: string
}

export type Players = Models.Row & {
  number: number
  name: string
  season: string
}

export type RedCards = Models.Row & {
  round: number
  player: number
  season: string
}

export type Seasons = Models.Row & {
  id: string
  order: number
  year: string
}

export type Standings = Models.Row & {
  played: number
  won: number
  drawn: number
  lost: number
  season: string
  team: Teams
}

export type Teams = Models.Row & {
  name: string
  owner: boolean
}

export type YellowCards = Models.Row & {
  round: number
  player: number
  amount: number
  season: string
}
